name: Java CI with multiple JDKs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 22 ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Build and test with Maven on JDK ${{ matrix.java }}
      run: mvn -B clean verify
